Allow 2-5 fingers to swipe and pinch
JoseExposito/touche pull request #82
Opened 2022-09-10 06:17 UTC by ichaoX

Relates to: #25

2022-09-11 16:56 UTC, JoseExposito commented
Hi @ichaoX 

Thanks for the pull request. As I mentioned in #25, gestures performed with 5 fingers or 2 fingers in case of pinch, are only available for touchscreens. Including them would probably confuse some users.

I like you approach to clarify in the title that they are touchscreen only but, what do you think about putting the new options inside an expander?

https://docs.gtk.org/gtk4/class.Expander.html

I think that it could be easier for the users to understand that those are touchscreen only settings.

2022-09-11 16:58 UTC, JoseExposito requested changes

2022-09-11 16:58 UTC, JoseExposito commented on src/main-view/content/pinch-view.js
> +
Please remove the trailing white spaces.

2022-09-11 16:58 UTC, JoseExposito commented on src/main-view/content/pinch-view.js
> +
Extra line

2022-09-11 18:18 UTC, ichaoX commented
Only available for touchscreens gestures have been put into expander.

2022-09-18 13:28 UTC, merged

2022-09-18 13:28 UTC, JoseExposito commented
Sorry for the delay looking into this, it's been a busy week. Merged, thanks a lot!